### ISSUE TITLE
Nested triples maps

### ISSUE THREAD

**Issue by dachafra** [kg-construct/mapping-challenges#6]
issue:  not possible to scope joins that will only occur within the scope of a single iteration

suggestion: add rml:subTriplesMap (or rml:nestedTriplesMap) as a property of rml:RefObjectMap. This will allow engines to resolve joins within a single iteration, covering the much occurring case where certain related objects only occur with the sub-hierarchy / sub-graph of other objects. This will also improve the streamability of mappings .

**Comment by bjdmeest** [comment]
Related discussion: https://github.com/kg-construct/rml-questions/discussions/11

**Comment by bjdmeest** [comment]
copying conclusion of https://github.com/kg-construct/rml-questions/discussions/11 here: what makes this trivial in, e.g., SPARQL-Anything, is the fact that values from the same iteration can be linked with some kind of 'iteration identifier' (that is independent of the actual data values).

> The issue is that a join needs some kind of join condition, whereas here, the join condition is basically 'be the same iteration'. If there would be a way to define this in RML, there would be no need for the current join condition.

Maybe it's a good idea to think of assigning each iteration with a some kind of ID by default, and have some way to refer to that id in the mapping? Or maybe even some additional functionality so we can do things like 'do join condition with the previous iteration' (in cases where order in a data source is actually meaningful), 'do join condition with the parent iteration' (in cases where data sources actually have hierarchy) etc.? That way, we keep a single construct in the RML language (i.e., join conditions), and the engines can optimize however they want. (no-one's to say we can't provide shortcuts as well ofc)

In fact, e.g., in JSONpath, part of the spec is to return the normalized path expression, as an alternative to the actual values, which we could see as the iteration ID? (see bottom of https://goessner.net/articles/JsonPath/ )

**Comment by bjdmeest** [comment]
I'm now wondering how much https://github.com/kg-construct/mapping-challenges/issues/20 (access fields in parent iteration) is actually this (join on iteration) + https://github.com/kg-construct/mapping-challenges/pull/29 (join to get literal instead of term) @frmichel do you think pushDown can be seen as syntactic sugar over 'join on parent iteration + get literal from join'?

**Comment by justin2004** [comment]
> do join condition with the parent iteration

@bjdmeest 

I need that often with JSON sources and when I tried to use RML I was able to do it by preprocessing the json and adding id keys ("_id") to each object and then I can reference them in the mapping to find the appropriate parent.

e.g. I changed [this](https://github.com/justin2004/rml-testing/blob/master/characters.json) to [this](https://github.com/justin2004/rml-testing/blob/master/rml/characters.pp.json).

[Here](https://github.com/justin2004/rml-testing/blob/master/rml/mapping.rml.ttl) is the RML that uses those id keys I added.

**Comment by frmichel** [comment]
> I'm now wondering how much kg-construct/rml-cc#5 (access fields in parent iteration) is actually this (join on iteration) + kg-construct/rml-core#29 (join to get literal instead of term) @frmichel do you think pushDown can be seen as syntactic sugar over 'join on parent iteration + get literal from join'?

Hi @bjdmeest, I'm not sure I get the whole picture here as I did not follow each of the issues, but I would say yes. The pushDown can be used not only in the rml:iterator but also in any sub-iteration made in a nested term map. Yet if you could send me an example that would help me be more specific.

**Comment by bjdmeest** [comment]
Hmmm, reiterating on this, this is getting very complex (see below for some pseudocode), probably it's better to take this into account when thinking about joins (as being discussed at https://github.com/kg-construct/rml-fno-spec/issues/2 )

```yaml
- triplesmap
  - logicalsource
    - iterator: $.parent[*]
  - subjectmap: "ex:{parentID}"
    class: "ex:Parent"
- triplesmap2
  - logicalsource
    - iterator: $.parent[*].child[*]
  - subjectmap: "ex:{childID}"
  - po
    - predicate: "ex:nestedName"
      object:
        function: joinvalues
        parameters:
        value1: "{childID}_" 
        value2:
          referencingobject:
            parenttriplesmap: triplesmap
            # joinOnSameParentIteration
            # from ParentIteration, take value "parentID"
```

**Comment by frmichel** [comment]
Ok I think I got it. So the answer is no, pushDown will not be sufficient in this case. I'll try to explain but I'm afraid that's not gonna be clear ;).

When you evaluate the iterator `$.parent[*].child[*]` on input documents, you mix up all parents and all children. You don't keep the association of parents to children. So this has to be done one hierarchical level at a time: first an iterator on parent[*], then on child[*].

The pushDown makes it possible to work one hierarchical level at a time, but it has a limitation: 
The first iteration level can be set in the logical source. Such that the fields pushed down from the logical source will be available for all term maps (subject, pred, and object).
The next levels will be set in (nested)term maps. But the fields pushed down from a (nested)term map will be available only for subsequent nested term maps, that is, within the context of either a unique subject map, or a unique object map, but not for both at the same time. Since the iterations in the subject map and the object map are not "in sync", that fails.

The example below will mix up all children from a given parent: the subject map will generate all terms "ex:{childID}" of a given parent, and those will be mixed them up with all (predicate object) couples for the same parent.

```yaml
 triplesmap2
  - logicalsource
    - iterator: $.parent[*]
    - pushdown:
      - reference: $.parent[*]
      - as: theParent
  - subjectmap:
        reference: $.child[*]
        nestedTermMap: "ex:{childID}"
  - po
    - predicate: "ex:nestedName"
      object:
        - reference: $.child[*]
        - pushdown:
          - reference: $.theParent
          - as: theParent
        - nestedTermMap: 
           - parenttriplesmap: triplesmap
           ... # some join condition involving theParent and parentID
```

I hope I answer your question, I'm still not sure I do ;).
